### ISSUE TITLE
Kindly provide these 2 files as I'm trying to run this project in my system. 

### ISSUE THREAD

**Issue by saxam0** [Jhaprince/BullyExplain#1]
@Jhaprince Kindly provide these 2 files as I'm trying to run this project in my system.

![WhatsApp Image 2024-04-04 at 13 49 58_55b7efd7](https://github.com/Jhaprince/BullyExplain/assets/97455464/23735153-7d7e-4d36-ae52-0d753c8964e9)

![WhatsApp Image 2024-04-04 at 13 50 09_360619f3](https://github.com/Jhaprince/BullyExplain/assets/97455464/731b308d-0190-4de7-94fc-0c9089f3ae45)

**Comment by saxam0** [comment]
> ![WhatsApp Image 2024-04-04 at 13 49 58_55b7efd7](https://private-user-images.githubusercontent.com/97455464/319504618-23735153-7d7e-4d36-ae52-0d753c8964e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTk2MTEsIm5iZiI6MTcxMjIxOTMxMSwicGF0aCI6Ii85NzQ1NTQ2NC8zMTk1MDQ2MTgtMjM3MzUxNTMtN2Q3ZS00ZDM2LWFlNTItMGQ3NTNjODk2NGU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA4MjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YWQ0OWI2NzU4MDljNjdiMGNmZWI2NzBiNmM2OWM2YmFmM2UyNmJjNDRhZTk0NzJiODRkMGMxMmFkOWQxMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLKK-5uiX6Ey5hqeFN8CvB6zhIDiYsHUGDk_N-91-7E)
> 
> ![WhatsApp Image 2024-04-04 at 13 50 09_360619f3](https://private-user-images.githubusercontent.com/97455464/319504671-731b308d-0190-4de7-94fc-0c9089f3ae45.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTk2MTEsIm5iZiI6MTcxMjIxOTMxMSwicGF0aCI6Ii85NzQ1NTQ2NC8zMTk1MDQ2NzEtNzMxYjMwOGQtMDE5MC00ZGU3LTk0ZmMtMGM5MDg5ZjNhZTQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA4MjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMjQ3ZmQ3YWVlOGE5ZTg2MTNhMWE5YzA3NWEyMGNlOGY1MTZkNzI3MWM3YWUxNGY3Y2E2YzU3YThjMjlkN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j46CzMJg_fcz4Hh7Uovp39cFWZ6wgrL49ronZxbS5B4)

@Jhaprince

**Comment by Jhaprince** [comment]
Updated the readme with the required link!

Thanks !
